[ids]
*
k:0001:0001

[main]
fn = layer(fn)
homepage = layer(meta)

[fn]
1 = S-1
2 = S-2
3 = S-3
4 = G-e
5 = S-5
6 = S-6
7 = S-7
8 = S-8
9 = S-9
0 = S-0
q = grave
w = G-2
e = G-4
u = G-7
i = G-8
o = G-9
p = G-0
r = G-S-0
l = backslash
k = kpasterisk
n = G-rightbrace
z = G-102nd
102nd = S-102nd
comma = S-comma
dot = S-dot
slash = S-slash
minus = S-minus
leftbrace = G-minus
rightbrace = S-rightbrace
equal = S-equal
semicolon = G-semicolon
apostrophe = G-apostrophe
